/**
 * Wrap the readable browser-half source into the client bundle DSH loads.
 *
 * The page receives `lib/client.js` through the client module system, so the
 * bundle must register itself on `window.__ModuleLoader__` and export `apply`
 * plus `inject`. This script adds exactly that wrapper; everything else comes
 * from `src/client.js`, which stays plain readable JavaScript.
 *
 * Usage: node scripts/build-client.mjs
 */
import { readFileSync, writeFileSync, statSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const SOURCE = join(ROOT, 'src', 'client.js')
const OUTPUT = join(ROOT, 'lib', 'client.js')

const { name: PACKAGE_NAME } = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))

const body = readFileSync(SOURCE, 'utf8').trimEnd()

const banner = [
  '/*',
  ` * ${PACKAGE_NAME} — generated by scripts/build-client.mjs.`,
  ` * Source: ${relative(ROOT, SOURCE).replaceAll('\\', '/')} — edit that file, then run \`npm run build\`.`,
  ' */',
].join('\n')

const bundle = `${banner}
window.__ModuleLoader__.load({id: '${PACKAGE_NAME}',factory: (require) => {var module = { exports: {} }
${body}
module.exports = { apply, inject }
return module.exports
},})
`

writeFileSync(OUTPUT, bundle)

const size = statSync(OUTPUT).size
console.log(`built ${relative(ROOT, OUTPUT).replaceAll('\\', '/')} (${(size / 1024).toFixed(1)} KiB)`)
